{% set name = "wsinfer" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wsinfer-{{ version }}.tar.gz
  sha256: b744c95d14e0c5561a118fae5713a585e910227cd0ebcf1dc2309e70667caa4d

build:
  noarch: python
  entry_points:
    - wsinfer = wsinfer.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - click >=8.0,<9,!=8.1.4,!=8.1.5
    - h5py
    - numpy
    - opencv >=4.0.0
    - openslide
    - openslide-python
    - pandas
    - pillow
    - scikit-image >=0.20.0
    - shapely
    - tifffile >=2023.1.23
    - tiffslide >=2.2.0
    - imagecodecs >=2022.7.27
    - pytorch >=1.7
    - torchvision
    - tqdm
    - wsinfer-zoo

test:
  imports:
    - wsinfer
  commands:
    - wsinfer --help

about:
  home: https://github.com/SBU-BMI/wsinfer
  summary: Run patch-based classification on pathology whole slide images.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://wsinfer.readthedocs.io/

extra:
  recipe-maintainers:
    - kaczmarj
